[package]
name = "rust_graphql"
version = "0.1.0"
authors = ["asashin227 <asa.shin.asa@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
